# Generated by Django 6.0.1 on 2026-01-09 20:07

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', api.models.MyAccountManager()),
            ],
        ),
    ]
